// SPDX-License-Identifier: GPL-2.0
/*
 * convlogo - Convert a BMP image to a C header for early boot logo
 *
 * Reads a 24-bit or 32-bit uncompressed BMP file and emits a C header
 * containing the image as an RGB888 byte array (3 bytes per pixel,
 * row-major, top-to-bottom). Output is suitable for direct inclusion
 * into kernel source for the early boot logo drawn to the system
 * framebuffer.
 *
 * Usage: convlogo -o <output.h> <input.bmp>
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#pragma pack(push, 1)

struct bmp_file_header {
	uint16_t magic;
	uint32_t file_size;
	uint32_t reserved;
	uint32_t pixel_offset;
};

struct bmp_dib_header {
	uint32_t header_size;
	int32_t  width;
	int32_t  height;
	uint16_t planes;
	uint16_t bpp;
	uint32_t compression;
	uint32_t image_size;
	int32_t  x_ppm;
	int32_t  y_ppm;
	uint32_t colors_used;
	uint32_t colors_important;
};

#pragma pack(pop)

#define BMP_MAGIC 0x4d42
#define BI_RGB    0

static const char *progname;

static void usage(void)
{
	fprintf(stderr, "Usage: %s -o <output.h> <input.bmp>\n", progname);
	exit(1);
}

int main(int argc, char **argv)
{
	const char *outpath = NULL;
	const char *inpath = NULL;
	FILE *fin, *fout;
	struct bmp_file_header fhdr;
	struct bmp_dib_header dhdr;
	uint8_t *pixels;
	long file_size;
	int i;

	progname = argv[0];

	for (i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "-o") && i + 1 < argc) {
			outpath = argv[++i];
		} else if (argv[i][0] != '-') {
			inpath = argv[i];
		} else {
			usage();
		}
	}

	if (!outpath || !inpath)
		usage();

	fin = fopen(inpath, "rb");
	if (!fin) {
		fprintf(stderr, "%s: cannot open '%s': ", progname, inpath);
		perror("");
		return 1;
	}

	if (fread(&fhdr, sizeof(fhdr), 1, fin) != 1) {
		fprintf(stderr, "%s: failed to read BMP file header\n",
			progname);
		fclose(fin);
		return 1;
	}

	if (fhdr.magic != BMP_MAGIC) {
		fprintf(stderr, "%s: '%s' is not a BMP file (magic 0x%04x)\n",
			progname, inpath, fhdr.magic);
		fclose(fin);
		return 1;
	}

	if (fhdr.pixel_offset < sizeof(fhdr) + sizeof(dhdr)) {
		fprintf(stderr,
			"%s: pixel data offset %u too small (headers end at %zu)\n",
			progname, fhdr.pixel_offset,
			sizeof(fhdr) + sizeof(dhdr));
		fclose(fin);
		return 1;
	}

	if (fread(&dhdr, sizeof(dhdr), 1, fin) != 1) {
		fprintf(stderr, "%s: failed to read BMP DIB header\n",
			progname);
		fclose(fin);
		return 1;
	}

	if (dhdr.header_size < sizeof(dhdr)) {
		fprintf(stderr,
			"%s: DIB header size %u too small (need >= %zu)\n",
			progname, dhdr.header_size, sizeof(dhdr));
		fclose(fin);
		return 1;
	}

	if (dhdr.compression != BI_RGB) {
		fprintf(stderr,
			"%s: unsupported compression %u (only c=0 supported)\n",
			progname, dhdr.compression);
		fclose(fin);
		return 1;
	}

	if (dhdr.bpp != 24 && dhdr.bpp != 32) {
		fprintf(stderr,
			"%s: unsupported bpp %u (only 24 and 32 supported)\n",
			progname, dhdr.bpp);
		fclose(fin);
		return 1;
	}

	if (dhdr.planes != 1) {
		fprintf(stderr, "%s: unsupported planes %u (must be 1)\n",
			progname, dhdr.planes);
		fclose(fin);
		return 1;
	}

	int width = dhdr.width;
	int height = dhdr.height;
	int bottom_up = 1;

	if (height < 0) {
		height = -height;
		bottom_up = 0;
	}

	if (width <= 0 || height <= 0) {
		fprintf(stderr, "%s: invalid dimensions %dx%d\n",
			progname, width, height);
		fclose(fin);
		return 1;
	}

	/* Row stride padded to 4-byte boundary (BMP requirement) */
	int row_bytes = (dhdr.bpp / 8) * width;
	int row_pad = (4 - (row_bytes % 4)) % 4;
	int padded_row = row_bytes + row_pad;

	/* Allocate and read raw pixel data */
	file_size = (long)padded_row * height;
	pixels = malloc(file_size);
	if (!pixels) {
		fprintf(stderr, "%s: out of memory (%ld bytes)\n",
			progname, file_size);
		fclose(fin);
		return 1;
	}

	if (fseek(fin, fhdr.pixel_offset, SEEK_SET) != 0) {
		fprintf(stderr, "%s: cannot seek to pixel data\n", progname);
		free(pixels);
		fclose(fin);
		return 1;
	}

	{
		long actual = (long)fread(pixels, 1, file_size, fin);

		if (actual != file_size) {
			fprintf(stderr,
				"%s: read short (%ld of %ld pixel bytes)\n",
				progname, actual, file_size);
			free(pixels);
			fclose(fin);
			return 1;
		}
	}

	fclose(fin);

	/* Write output header */
	fout = fopen(outpath, "w");
	if (!fout) {
		fprintf(stderr, "%s: cannot create '%s': ", progname, outpath);
		perror("");
		free(pixels);
		return 1;
	}

	fprintf(fout, "/* SPDX-License-Identifier: GPL-2.0 */\n");
	fprintf(fout, "/*\n");
	fprintf(fout, " * Auto-generated by convlogo from '%s' — do not edit.\n",
		inpath);
	fprintf(fout, " */\n\n");
	fprintf(fout, "#ifndef __EARLY_LOGO_H\n");
	fprintf(fout, "#define __EARLY_LOGO_H\n\n");
	fprintf(fout, "#include <linux/init.h>\n\n");
	fprintf(fout, "static const unsigned int early_logo_width = %d;\n",
		width);
	fprintf(fout, "static const unsigned int early_logo_height = %d;\n",
		height);
	fprintf(fout, "\nstatic const unsigned char early_logo_data[] __initdata = {\n");

	/*
	 * Emit pixels in top-to-bottom, left-to-right order as RGB888
	 * (3 bytes per pixel). BMP stores pixels as BGR, so swap R and B.
	 * BMP rows are padded; we skip the padding bytes.
	 */
	int bytes_per_pixel = dhdr.bpp / 8;

	for (int y = 0; y < height; y++) {
		int src_y = bottom_up ? (height - 1 - y) : y;
		uint8_t *row = pixels + (long)src_y * padded_row;

		for (int x = 0; x < width; x++) {
			uint8_t b = row[x * bytes_per_pixel + 0];
			uint8_t g = row[x * bytes_per_pixel + 1];
			uint8_t r = row[x * bytes_per_pixel + 2];

			fprintf(fout, "0x%02x, 0x%02x, 0x%02x,", r, g, b);
			if ((x % 5) == 4)
				fprintf(fout, "\n");
		}

		if (width % 5 != 4)
			fprintf(fout, "\n");
	}

	fprintf(fout, "};\n\n");
	fprintf(fout, "#endif /* __EARLY_LOGO_H */\n");

	free(pixels);
	fclose(fout);

	return 0;
}
